export var msg= {
    root: {
        // LOGIN
        "login.title": "Sign in to your account",
        "login.instr": "Please enter your credentials:",
        "login.username": "Username",
        "login.password": "Password",
        "login.button": "Sign in",
        "logout.title":"Session ended",
        "logout.instr":"Your session has ended. You may start a new session or close your browser window.",
        "logout.button":"New session",
        "login.errorH": "Authentication failed",
        "login.errorC": "Error message:",
        "login.errorB": "Try again",
        "login.invalidUserPassword": "Invalid Username or Password.",
        "login.failedToAuthenticate": "Failed to Authenticate.",
        "login.noAccessMessage": "Access to this application is forbidden.",
        "login.configurationError": "Security module initialization failed. Please check server logs for details.",
        "login.serverNotAvailable": "Sorry, the Server is not available.",
        "login.unexpectedError": "Oops, something's not right",

        // DIALOG
        "dialog.emptyMessage": "",
        "dialog.logingOut": "Signing out",
        "dialog.readyDialog": "Ready to start your session",
        "dialog.initializingDialog": "Your session is being initialized",
        "dialog.startingDialog": "Starting your application",
        "dialog.unauthorizedAccess": "Unable to authorize your request",
        "dialog.applicationBusyDialog": "",
        "dialog.applicationAlreadyRunning": "There is already a session in progress in another window.",
        "dialog.sessionStolenNotification": "A new session was started in another window. This session has been closed.",
        "dialog.disconnectedDialog": "Your connection to the server is lost.",
        "dialog.connectionErrorDialog": "A connection error has occurred. Please reconnect to continue.",
        "dialog.tooManyClientsNotification": "There are too many active connections right now, please try again later.",
        "dialog.stoppedDialog": "The application has been closed.",
        "dialog.timedoutDialog": "The session has timed out.",
        "dialog.continueH": "Welcome back!",
        "dialog.continueC1": "You can continue where you left off or ",
        "dialog.continueC2": "start again",
        "dialog.longPollingH": "Warning",
        "dialog.longPollingC": "Your current network blocks WebSockets. You may experience performance problems while working on this connection. Please contact your network administrator.",
        "dialog.longPollingB": "Dismiss",
        "dialog.inactivityTimeoutH": "Warning",
        "dialog.inactivityTimeoutC": "Your session will timeout in less then a minute due to inactivity. Please press any button to continue.",
        "dialog.inactivityTimeoutB": "Dismiss",
        "dialog.finalB1": "New session",
        "dialog.finalB2": "Sign out",
        "dialog.retryB1": "Reconnect",
        "dialog.retryB2": "Sign out",
        "dialog.networkMonitor.warn":"Your network connection is slow.",
        "dialog.networkMonitor.offline":"No network connection.",
        "dialog.networkMonitor.hide":"Hide",
        "dialog.cookiesDisabledDialog": "Your browser does not allow cookies. Please enable cookies to continue.",
        "dialog.touchSwitchMode.mouse": "Do you want to switch to mouse mode?",
        "dialog.touchSwitchMode.touch": "Do you want to switch to touch mode?",
        "dialog.touchSwitchMode.switchButton": "Switch",
        "dialog.touchSwitchMode.cancelButton": "Hide",
        "dialog.overlay.docking.visibility": "Main Webswing window has been hidden. Please make sure the main window is visible to continue.",
        "dialog.overlay.docking.modality": "This window is blocked by another modal window.",
        "dialog.overlay.docking.focusWindow": "Show window",
        
        //  SELECTOR
        "selector.welcome": "Welcome,",
        "selector.message": ". Please select an application.",
        "selector.lang.label": "Language: ",
        "selector.admin": "Manage",
        "selector.logout": "Logout",
        "selector.noApp": "There are currently no available applications.",

        //  CLIPBOARD
        "clipboard.content": "Content",
        "clipboard.image": "Image:",
        "clipboard.files": "Files:",
        "clipboard.copy": "Copy to Clipboard (CTRL+C)",
        "clipboard.more": "More...",
        "clipboard.discard": "Discard",
        "clipboard.cancel": "Cancel",
        "clipboard.paste.title.touch": "Please paste content",
        "clipboard.paste.message.touch": "Press and hold on the input below to paste from clipboard.",

        //  FILES
        "files.saveTitle": "Save file",
        "files.saveName": "Please enter a name for the file.",
        "files.saveNamePh": "Enter a file name here",
        "files.save": "Save",
        "files.saveInvlidFilename": "File name is invalid. Please use only alphanumeric characters, space, hyphen, dot or underscore.",
        "files.openTitle": "Open file",
        "files.openInst": "Please select a file to import.",
        "files.openBrowse": "Browse",
        "files.dnd": "Drag and drop files here",
        "files.download": "Download",
        "files.downloadTtip": "Download selected files",
        "files.upload": "Upload",
        "files.delete": "Delete",
        "files.deleteTtip": "Delete selected files",
        "files.cancel": "Cancel",
        "files.progress": "Progress:",
        "files.progComplete": "Complete",
        "files.uploadComplete": "Upload complete",
        "files.downloadLink.link.title": "Open link",
        "files.downloadLink.link.message": "Please click the button below to open link.",
        "files.downloadLink.link.button": "Open",
        "files.downloadLink.download.title": "Download file",
        "files.downloadLink.download.message": "Please click the button below to download the file.",
        "files.downloadLink.download.button": "Download",
        "files.downloadLink.print.title": "Print",
        "files.downloadLink.print.message": "Please click the button below to view the printed file.",
        "files.downloadLink.print.button": "View",
        
        //  TOUCH
        "touch.controlMode": "Control Mode",
        "touch.desktopMode": "Desktop Mode",
        "touch.copy": "Copy",
        "touch.cut": "Cut",
        "touch.paste": "Paste",
        "touch.keyboard": "Keyboard",
        "touch.fullscreen": "Fullscreen",
        	
        //   ACCESSIBILITY
        "accessibility.turnOn": "To turn accessibility feature on or off press CTRL 5 times. To switch between windows press CTRL 3 times. To focus out of a table or text area press ESCAPE or SHIFT ESCAPE.",
        "accessibility.turnedOn": "Accessibility turned on.",
        "accessibility.turnedOff": "Accessibility turned off.",
        "accessibility.window.button.toggleDock": "Toggle dock",
        "accessibility.window.button.close": "Close",
        "accessibility.window.button.restore": "Restore",
        "accessibility.window.button.minimize": "Minimize",
        "accessibility.window.button.maximize": "Maximize",
        "accessibility.switcher.title": "Select Window",
        "accessibility.switcher.cancel": "Cancel",
        "accessibility.switcher.untitled": "untitled window",
       	"accessibility.switcher.description": "Press Enter to activate selected window, press X to close the window.",
       	"accessibility.switcher.modalBlocked": "(blocked by modal)",
     	"accessibility.switcher.modalBlocked.description": "This window is blocked by another modal window. You cannot activate or close it."
        
    }
}