define({
    root: {
        // LOGIN
        "login.title": "Sign in to your account",
        "login.instr": "Please enter your credentials:",
        "login.username": "Username",
        "login.password": "Password",
        "login.button": "Sign in",
        "logout.title":"Session ended",
        "logout.instr":"Your session has ended. You may start a new session or close your browser window.",
        "logout.button":"New session",
        "login.ssoErrorH": "Single Sign-On authentication failed",
        "login.ssoErrorC": "Error message:",
        "login.ssoErrorB": "Try again",
        "login.invalidUserPassword": "Invalid Username or Password.",
        "login.failedToAuthenticate": "Failed to Authenticate.",
        "login.serverNotAvailable": "Sorry, the Server is not available.",
        "login.unexpectedError": "Oops, something's not right",

        // DIALOG
        "dialog.emptyMessage": "",
        "dialog.logingOut": "Signing out",
        "dialog.readyDialog": "Ready to start your session",
        "dialog.initializingDialog": "Your session is being initialized",
        "dialog.startingDialog": "Starting your application",
        "dialog.unauthorizedAccess": "Unable to authorize your request",
        "dialog.applicationAlreadyRunning": "There is already a session in progress in another window.",
        "dialog.sessionStolenNotification": "A new session was started in another window. This session has been closed.",
        "dialog.disconnectedDialog": "You have been disconnected from the server. Please reconnect to continue.",
        "dialog.connectionErrorDialog": "A connection error has occurred. Please reconnect to continue.",
        "dialog.tooManyClientsNotification": "There are too many active connections right now, please try again later.",
        "dialog.stoppedDialog": "The application has been closed.",
        "dialog.timedoutDialog": "The session has timed out.",
        "dialog.continueC": "Welcome back! <br>You can continue working in your previous session.",
        "dialog.continueB1": "Restart session",
        "dialog.continueB2": "Dismiss",
        "dialog.longPollingH": "Warning",
        "dialog.longPollingC": "Your current network blocks WebSockets. You may experience performance problems while working on this connection. Please contact your network administrator.",
        "dialog.longPollingB": "Dismiss",
        "dialog.inactivityTimeoutH": "Warning",
        "dialog.inactivityTimeoutC": "Your session will timeout in less then a minute due to inactivity. Please press any button to continue.",
        "dialog.inactivityTimeoutB": "Dismiss",
        "dialog.finalB1": "New session",
        "dialog.finalB2": "Sign out",
        "dialog.retryB1": "Reconnect",
        "dialog.retryB2": "Sign out",

        //  SELECTOR
        "selector.welcome": "Welcome,",
        "selector.message": ". Please select an application.",
        "selector.lang.label": "Language: ",
        "selector.admin": "Manage",
        "selector.logout": "Logout",
        "selector.noApp": "There are currently no available applications.",

        //  CLIPBOARD
        "clipboard.content": "Content",
        "clipboard.image": "Image:",
        "clipboard.files": "Files:",
        "clipboard.copy": "Copy to Clipboard (CTRL+C)",
        "clipboard.more": "More...",
        "clipboard.discard": "Discard",

        //  FILES
        "files.saveTitle": "Save file",
        "files.saveName": "Please enter a name for the file.",
        "files.saveNamePh": "Enter a file name here",
        "files.save": "Save",
        "files.saveInvlidFilename": "File name is invalid. Please use only alphanumeric characters, space, hyphen, dot or underscore.",
        "files.openTitle": "Open file",
        "files.openInst": "Please select a file to import.",
        "files.openBrowse": "Browse",
        "files.dnd": "Drag and drop files here",
        "files.download": "Download",
        "files.downloadTtip": "Download selected files",
        "files.upload": "Upload",
        "files.delete": "Delete",
        "files.deleteTtip": "Delete selected files",
        "files.cancel": "Cancel",
        "files.progress": "Progress:",
        "files.progComplete": "Complete"
    }
})